import { Species } from '../types';

export const IMAGES = {
  Mammal: require('../../assets/wildlife/mammals.jpg'),
  Bird: require('../../assets/wildlife/birds.jpg'),
  Butterfly: require('../../assets/wildlife/butterflies.jpg'),
  Reptile: require('../../assets/wildlife/reptiles.jpg'),
  marmoset: require('../../assets/wildlife/marmoset.jpg'),
  tapir: require('../../assets/wildlife/malayan-tapir-card.jpg'),
  recent: require('../../assets/wildlife/recent-marmoset.jpg'),
};

export const DISCOVERY_CATEGORY_IMAGES = {
  Mammal: require('../../assets/discovery/mammals.png'),
  Bird: require('../../assets/discovery/birds.png'),
  Butterfly: require('../../assets/discovery/butterflies.png'),
  Reptile: require('../../assets/discovery/reptiles.png'),
};

export const HOME_IMAGES = {
  brandLogo: require('../../assets/home/brand-logo.png'),
  leafDecor: require('../../assets/home/image-decor.png'),
  pandaDecor: require('../../assets/home/red-panda-bush-deco.png'),
  collectionBook: require('../../assets/home/collection-book.png'),
  tileDiscover: require('../../assets/home/tile-discover.png'),
  tileCapture: require('../../assets/home/tile-capture.png'),
  tileBattle: require('../../assets/home/tile-battle.png'),
};

export const COLLECTION_IMAGES = {
  vineBottomLeft: require('../../assets/collection/vine-bottom-left.png'),
  tigerTopRight: require('../../assets/collection/tiger-top-right.png'),
  vineBottomRight: require('../../assets/collection/vine-bottom-right.png'),
};

export const AUTH_IMAGES = {
  mascotWelcome: require('../../assets/auth/mascot-id-card.png'),
  mascotLogin: require('../../assets/auth/mascot-wave.png'),
  mascotForgot: require('../../assets/auth/mascot-key.png'),
  mascotReset: require('../../assets/auth/mascot-shield.png'),
  avatarBird: require('../../assets/auth/avatar-bird.png'),
  avatarTiger: require('../../assets/auth/avatar-tiger.png'),
  avatarPanda: require('../../assets/auth/avatar-panda.png'),
};

export const DEFAULT_AVATAR = 'hornbill';

export const AVATAR_CHOICES = [
  { key: 'hornbill', label: 'Hornbill', image: AUTH_IMAGES.avatarBird },
  { key: 'tiger', label: 'Tiger', image: AUTH_IMAGES.avatarTiger },
  { key: 'panda', label: 'Panda', image: AUTH_IMAGES.avatarPanda },
] as const;

export const AVATAR_IMAGES: Record<string, number> = Object.fromEntries(
  AVATAR_CHOICES.map((choice) => [choice.key, choice.image]),
);

export function avatarImageFor(avatar: string): number {
  return AVATAR_IMAGES[avatar] || AUTH_IMAGES.avatarBird;
}

export const SPECIES_IMAGES: Record<string, number> = {
  sp_asian_elephant: require('../../assets/species/sp_asian_elephant.jpg'),
  sp_common_mormon: require('../../assets/species/sp_common_mormon.jpg'),
  sp_green_sea_turtle: require('../../assets/species/sp_green_sea_turtle.jpg'),
  sp_malayan_pangolin: require('../../assets/species/sp_malayan_pangolin.jpg'),
  sp_malayan_tapir: require('../../assets/species/sp_malayan_tapir.jpg'),
  sp_malayan_tiger: require('../../assets/species/sp_malayan_tiger.jpg'),
  sp_mouse_deer: require('../../assets/species/sp_mouse_deer.jpg'),
  sp_oriental_pied_hornbill: require('../../assets/species/sp_oriental_pied_hornbill.jpg'),
  sp_proboscis_monkey: require('../../assets/species/sp_proboscis_monkey.jpg'),
  sp_reticulated_python: require('../../assets/species/sp_reticulated_python.jpg'),
  sp_rhinoceros_hornbill: require('../../assets/species/sp_rhinoceros_hornbill.jpg'),
  sp_saltwater_crocodile: require('../../assets/species/sp_saltwater_crocodile.jpg'),
  sp_sunda_colugo: require('../../assets/species/sp_sunda_colugo.jpg'),
  sp_sun_bear: require('../../assets/species/sp_sun_bear.jpg'),
  sp_tailed_jay: require('../../assets/species/sp_tailed_jay.jpg'),
};

Object.assign(SPECIES_IMAGES, {
  sp_ashy_tailorbird: require('../../assets/species/sp_ashy_tailorbird.jpg'),
  sp_asian_blue_quail: require('../../assets/species/sp_asian_blue_quail.jpg'),
  sp_asian_small_clawed_otter: require('../../assets/species/sp_asian_small_clawed_otter.jpg'),
  sp_asiatic_brush_tailed_porcupine: require('../../assets/species/sp_asiatic_brush_tailed_porcupine.jpg'),
  sp_asiatic_golden_cat: require('../../assets/species/sp_asiatic_golden_cat.jpg'),
  sp_asiatic_striped_squirrels: require('../../assets/species/sp_asiatic_striped_squirrels.jpg'),
  sp_banded_civet: require('../../assets/species/sp_banded_civet.jpg'),
  sp_banded_leaf_monkey: require('../../assets/species/sp_banded_leaf_monkey.jpg'),
  sp_banded_linsang: require('../../assets/species/sp_banded_linsang.jpg'),
  sp_banteng: require('../../assets/species/sp_banteng.jpg'),
  sp_barred_eagle_owl: require('../../assets/species/sp_barred_eagle_owl.jpg'),
  sp_bearded_pig: require('../../assets/species/sp_bearded_pig.jpg'),
  sp_binturong: require('../../assets/species/sp_binturong.jpg'),
  sp_black_crowned_pitta: require('../../assets/species/sp_black_crowned_pitta.jpg'),
  sp_black_giant_squirrel: require('../../assets/species/sp_black_giant_squirrel.jpg'),
  sp_blue_breasted_quail: require('../../assets/species/sp_blue_breasted_quail.jpg'),
  sp_blue_headed_pitta: require('../../assets/species/sp_blue_headed_pitta.jpg'),
  sp_blyth_s_hawk_eagle: require('../../assets/species/sp_blyth_s_hawk_eagle.jpg'),
  sp_bornean_banded_pitta: require('../../assets/species/sp_bornean_banded_pitta.jpg'),
  sp_bornean_orangutan: require('../../assets/species/sp_bornean_orangutan.jpg'),
  sp_bornean_partridge: require('../../assets/species/sp_bornean_partridge.jpg'),
  sp_bornean_yellow_muntjac: require('../../assets/species/sp_bornean_yellow_muntjac.jpg'),
  sp_borneo_bay_cat: require('../../assets/species/sp_borneo_bay_cat.jpg'),
  sp_borneo_earless_monitor: require('../../assets/species/sp_borneo_earless_monitor.jpg'),
  sp_brown_rat: require('../../assets/species/sp_brown_rat.jpg'),
  sp_black_rumped_flameback: require('../../assets/species/sp_black_rumped_flameback.jpg'),
  sp_buffy_fish_owl: require('../../assets/species/sp_buffy_fish_owl.jpg'),
  sp_changeable_hawk_eagle: require('../../assets/species/sp_changeable_hawk_eagle.jpg'),
  sp_chestnut_capped_babbler: require('../../assets/species/sp_chestnut_capped_babbler.jpg'),
  sp_chestnut_capped_thrush: require('../../assets/species/sp_chestnut_capped_thrush.jpg'),
  sp_cinereous_bulbul: require('../../assets/species/sp_cinereous_bulbul.jpg'),
  sp_clouded_leopard: require('../../assets/species/sp_clouded_leopard.jpg'),
  sp_collared_mongoose: require('../../assets/species/sp_collared_mongoose.jpg'),
  sp_common_emerald_dove: require('../../assets/species/sp_common_emerald_dove.jpg'),
  sp_common_hill_myna: require('../../assets/species/sp_common_hill_myna.jpg'),
  sp_common_palm_civet: require('../../assets/species/sp_common_palm_civet.jpg'),
  sp_common_sun_skink: require('../../assets/species/sp_common_sun_skink.jpg'),
  sp_common_treeshrew: require('../../assets/species/sp_common_treeshrew.jpg'),
  sp_common_water_monitor: require('../../assets/species/sp_common_water_monitor.jpg'),
  sp_crab_eating_macaque: require('../../assets/species/sp_crab_eating_macaque.jpg'),
  sp_crab_eating_mongoose: require('../../assets/species/sp_crab_eating_mongoose.jpg'),
  sp_crested_partridge: require('../../assets/species/sp_crested_partridge.jpg'),
  sp_crested_serpent_eagle: require('../../assets/species/sp_crested_serpent_eagle.jpg'),
  sp_crimson_headed_partridge: require('../../assets/species/sp_crimson_headed_partridge.jpg'),
  sp_crimson_winged_woodpecker: require('../../assets/species/sp_crimson_winged_woodpecker.jpg'),
  sp_dark_necked_tailorbird: require('../../assets/species/sp_dark_necked_tailorbird.jpg'),
  sp_dhole: require('../../assets/species/sp_dhole.jpg'),
  sp_dusky_leaf_monkey: require('../../assets/species/sp_dusky_leaf_monkey.jpg'),
  sp_flat_headed_cat: require('../../assets/species/sp_flat_headed_cat.jpg'),
  sp_four_striped_ground_squirrel: require('../../assets/species/sp_four_striped_ground_squirrel.jpg'),
  sp_gaur: require('../../assets/species/sp_gaur.jpg'),
  sp_great_argus: require('../../assets/species/sp_great_argus.jpg'),
  sp_greater_coucal: require('../../assets/species/sp_greater_coucal.jpg'),
  sp_greater_oriental_chevrotain: require('../../assets/species/sp_greater_oriental_chevrotain.jpg'),
  sp_green_backed_heron: require('../../assets/species/sp_green_backed_heron.jpg'),
  sp_green_billed_coucal: require('../../assets/species/sp_green_billed_coucal.jpg'),
  sp_grey_bellied_squirrel: require('../../assets/species/sp_grey_bellied_squirrel.jpg'),
  sp_honey_buzzard: require('../../assets/species/sp_honey_buzzard.jpg'),
  sp_hose_s_civet: require('../../assets/species/sp_hose_s_civet.jpg'),
  sp_hose_s_langur: require('../../assets/species/sp_hose_s_langur.jpg'),
  sp_indomalayan_bamboo_rat: require('../../assets/species/sp_indomalayan_bamboo_rat.jpg'),
  sp_lar_gibbon: require('../../assets/species/sp_lar_gibbon.jpg'),
  sp_large_indian_civet: require('../../assets/species/sp_large_indian_civet.jpg'),
  sp_large_spotted_civet: require('../../assets/species/sp_large_spotted_civet.jpg'),
  sp_large_treeshrew: require('../../assets/species/sp_large_treeshrew.jpg'),
  sp_leopard: require('../../assets/species/sp_leopard.jpg'),
  sp_lesser_dog_faced_fruit_bat: require('../../assets/species/sp_lesser_dog_faced_fruit_bat.jpg'),
  sp_long_tailed_porcupine: require('../../assets/species/sp_long_tailed_porcupine.jpg'),
  sp_long_tailed_sibia: require('../../assets/species/sp_long_tailed_sibia.jpg'),
  sp_mainland_leopard_cat: require('../../assets/species/sp_mainland_leopard_cat.jpg'),
  sp_malay_banded_pitta: require('../../assets/species/sp_malay_banded_pitta.jpg'),
  sp_malay_civet: require('../../assets/species/sp_malay_civet.jpg'),
  sp_malay_crested_fireback: require('../../assets/species/sp_malay_crested_fireback.jpg'),
  sp_malay_ground_cuckoo: require('../../assets/species/sp_malay_ground_cuckoo.jpg'),
  sp_malay_weasel: require('../../assets/species/sp_malay_weasel.jpg'),
  sp_malayan_night_heron: require('../../assets/species/sp_malayan_night_heron.jpg'),
  sp_malayan_peacock_pheasant: require('../../assets/species/sp_malayan_peacock_pheasant.jpg'),
  sp_malayan_porcupine: require('../../assets/species/sp_malayan_porcupine.jpg'),
  sp_malaysian_field_rat: require('../../assets/species/sp_malaysian_field_rat.jpg'),
  sp_malaysian_rail_babbler: require('../../assets/species/sp_malaysian_rail_babbler.jpg'),
  sp_marbled_cat: require('../../assets/species/sp_marbled_cat.jpg'),
  sp_maroon_sureli: require('../../assets/species/sp_maroon_sureli.jpg'),
  sp_masked_palm_civet: require('../../assets/species/sp_masked_palm_civet.jpg'),
  sp_moonrat: require('../../assets/species/sp_moonrat.jpg'),
  sp_mountain_imperial_pigeon: require('../../assets/species/sp_mountain_imperial_pigeon.jpg'),
  sp_noisy_rat: require('../../assets/species/sp_noisy_rat.jpg'),
  sp_northern_treeshrew: require('../../assets/species/sp_northern_treeshrew.jpg'),
  sp_orange_headed_thrush: require('../../assets/species/sp_orange_headed_thrush.jpg'),
  sp_oriental_magpie_robin: require('../../assets/species/sp_oriental_magpie_robin.jpg'),
  sp_otter_civet: require('../../assets/species/sp_otter_civet.jpg'),
  sp_pale_giant_squirrel: require('../../assets/species/sp_pale_giant_squirrel.jpg'),
  sp_plantain_squirrel: require('../../assets/species/sp_plantain_squirrel.jpg'),
  sp_prevost_s_squirrel: require('../../assets/species/sp_prevost_s_squirrel.jpg'),
  sp_red_junglefowl: require('../../assets/species/sp_red_junglefowl.jpg'),
  sp_roughneck_monitor: require('../../assets/species/sp_roughneck_monitor.jpg'),
  sp_rufous_browed_babbler: require('../../assets/species/sp_rufous_browed_babbler.jpg'),
  sp_rufous_tailed_pheasant: require('../../assets/species/sp_rufous_tailed_pheasant.jpg'),
  sp_rufous_tailed_shama: require('../../assets/species/sp_rufous_tailed_shama.jpg'),
  sp_sambar: require('../../assets/species/sp_sambar.jpg'),
  sp_serow: require('../../assets/species/sp_serow.jpg'),
  sp_short_tailed_babbler: require('../../assets/species/sp_short_tailed_babbler.jpg'),
  sp_short_tailed_mongoose: require('../../assets/species/sp_short_tailed_mongoose.jpg'),
  sp_small_indian_mongoose: require('../../assets/species/sp_small_indian_mongoose.jpg'),
  sp_small_toothed_palm_civet: require('../../assets/species/sp_small_toothed_palm_civet.jpg'),
  sp_smooth_coated_otter: require('../../assets/species/sp_smooth_coated_otter.jpg'),
  sp_sooty_capped_babbler: require('../../assets/species/sp_sooty_capped_babbler.jpg'),
  sp_southern_pig_tailed_macaque: require('../../assets/species/sp_southern_pig_tailed_macaque.jpg'),
  sp_southern_red_muntjac: require('../../assets/species/sp_southern_red_muntjac.jpg'),
  sp_spotted_giant_flying_squirrel: require('../../assets/species/sp_spotted_giant_flying_squirrel.jpg'),
  sp_striped_wren_babbler: require('../../assets/species/sp_striped_wren_babbler.jpg'),
  sp_stump_tailed_macaque: require('../../assets/species/sp_stump_tailed_macaque.jpg'),
  sp_sunda_clouded_leopard: require('../../assets/species/sp_sunda_clouded_leopard.jpg'),
  sp_sunda_laughingthrush: require('../../assets/species/sp_sunda_laughingthrush.jpg'),
  sp_sunda_pied_fantail: require('../../assets/species/sp_sunda_pied_fantail.jpg'),
  sp_sunda_stink_badger: require('../../assets/species/sp_sunda_stink_badger.jpg'),
  sp_thick_spined_porcupine: require('../../assets/species/sp_thick_spined_porcupine.jpg'),
  sp_three_striped_ground_squirrel: require('../../assets/species/sp_three_striped_ground_squirrel.jpg'),
  sp_tiger_shrike: require('../../assets/species/sp_tiger_shrike.jpg'),
  sp_tufted_ground_squirrel: require('../../assets/species/sp_tufted_ground_squirrel.jpg'),
  sp_vieillot_s_fireback: require('../../assets/species/sp_vieillot_s_fireback.jpg'),
  sp_western_hooded_pitta: require('../../assets/species/sp_western_hooded_pitta.jpg'),
  sp_white_breasted_waterhen: require('../../assets/species/sp_white_breasted_waterhen.jpg'),
  sp_white_crested_hornbill: require('../../assets/species/sp_white_crested_hornbill.jpg'),
  sp_white_crowned_forktail: require('../../assets/species/sp_white_crowned_forktail.jpg'),
  sp_white_fronted_langur: require('../../assets/species/sp_white_fronted_langur.jpg'),
  sp_white_rumped_shama: require('../../assets/species/sp_white_rumped_shama.jpg'),
  sp_white_tailed_wattled_pheasant: require('../../assets/species/sp_white_tailed_wattled_pheasant.jpg'),
  sp_white_thighed_surili: require('../../assets/species/sp_white_thighed_surili.jpg'),
  sp_wild_boar: require('../../assets/species/sp_wild_boar.jpg'),
  sp_yellow_bellied_bulbul: require('../../assets/species/sp_yellow_bellied_bulbul.jpg'),
  sp_yellow_handed_mitered_langur: require('../../assets/species/sp_yellow_handed_mitered_langur.jpg'),
  sp_yellow_rumped_flycatcher: require('../../assets/species/sp_yellow_rumped_flycatcher.jpg'),
  sp_yellow_throated_marten: require('../../assets/species/sp_yellow_throated_marten.jpg'),
  sp_chestnut_necklaced_partridge: require('../../assets/species/sp_chestnut_necklaced_partridge.jpg'),
  sp_horse_tailed_squirrel: require('../../assets/species/sp_horse_tailed_squirrel.jpg'),
  sp_shrew_faced_squirrel: require('../../assets/species/sp_shrew_faced_squirrel.jpg'),
});

export function imageFor(species: Species): number | undefined {
  return SPECIES_IMAGES[species.id];
}

export function hasReferenceImage(species: Species): boolean {
  return Boolean(imageFor(species));
}
