"use client";
import { useEffect, useMemo, useState } from "react";

type Species = { id:string; common_name:string; scientific_name:string; category:string; habitat:string; diet:string; fun_fact:string; image_url:string; act716_status?:string };
type Page = "home"|"category"|"species"|"confirm"|"success"|"collection"|"about"|"facts"|"gallery"|"locked"|"progress";
const API = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000";
const fallback: Species[] = [
  {id:"sp_common_mormon",common_name:"Common Mormon",scientific_name:"Papilio polytes",category:"Butterfly",habitat:"Gardens, parks and forest edges across Malaysia.",diet:"Flower nectar",fun_fact:"Some females copy the look of a poisonous butterfly.",image_url:"/images/butterflies.jpg"},
  {id:"sp_malayan_tapir",common_name:"Malayan Tapir",scientific_name:"Tapirus indicus",category:"Mammal",habitat:"Rainforest, often near water.",diet:"Leaves, shoots and fruit.",fun_fact:"Babies are born with stripes and spots.",image_url:"/images/malayan-tapir-card.jpg"},
  {id:"sp_oriental_pied_hornbill",common_name:"Oriental Pied Hornbill",scientific_name:"Anthracoceros albirostris",category:"Bird",habitat:"Lowland forests and gardens.",diet:"Fruit, insects and small animals.",fun_fact:"It makes a distinctive flapping sound.",image_url:"/images/birds.jpg"},
  {id:"sp_common_water_monitor",common_name:"Common Water Monitor",scientific_name:"Varanus salvator",category:"Reptile",habitat:"Wetlands and forest edges.",diet:"Small animals and eggs.",fun_fact:"It is an excellent swimmer.",image_url:"/images/reptiles.jpg"},
];
const categoryImages: Record<string,string> = { Mammal:"/images/mammals.jpg", Bird:"/images/birds.jpg", Butterfly:"/images/butterflies.jpg", Reptile:"/images/reptiles.jpg" };

export default function App(){
 const [page,setPage]=useState<Page>("home"), [all,setAll]=useState<Species[]>(fallback), [chosen,setChosen]=useState<Species>(fallback[0]), [category,setCategory]=useState("Mammal"), [discovered,setDiscovered]=useState<string[]>([]), [tab,setTab]=useState<Page>("about"), [filter,setFilter]=useState("All"), [progress,setProgress]=useState({found:0,total:20,xp:0,categories:[] as {category:string,total:number,discovered:number}[]});
 const refresh=async()=>{try{const [s,c,p]=await Promise.all([fetch(`${API}/api/v1/species`),fetch(`${API}/api/v1/children/1/collection`),fetch(`${API}/api/v1/children/1/progress`)]); if(s.ok)setAll(await s.json()); if(c.ok)setDiscovered((await c.json()).items.filter((x:{discovered:number})=>x.discovered).map((x:{id:string})=>x.id)); if(p.ok){const x=await p.json();setProgress({found:x.found,total:x.total,xp:x.profile.xp,categories:x.categories})}}catch{/* static fallback remains usable */}};
 useEffect(()=>{refresh()},[]);
 const items=useMemo(()=>all.filter(x=>filter==="All"||x.category===filter),[all,filter]);
 const go=(next:Page)=>{setPage(next); if(["about","facts","gallery"].includes(next))setTab(next)};
 const select=(s:Species)=>{setChosen(s);go("confirm")};
 const confirm=async()=>{try{const r=await fetch(`${API}/api/v1/children/1/discoveries`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({species_id:chosen.id,location_label:"Kuala Lumpur, Malaysia"})});if(r.ok)await refresh()}finally{go("success")}};
 const nav=(to:Page)=>go(to);
 const Header=({title,back=true}:{title:string,back?:boolean})=><header className="top">{back&&<button className="round" aria-label="Go back" onClick={()=>go("home")}>←</button>}<h1>{title}</h1></header>;
 const Bottom=()=> <nav className="bottom"><button onClick={()=>nav("home")}>⌂<span>Home</span></button><button onClick={()=>nav("category")}>⌕<span>Explore</span></button><button className="record" aria-label="Record a discovery" onClick={()=>nav("category")}>＋</button><button onClick={()=>nav("collection")}>▣<span>Collection</span></button><button onClick={()=>nav("progress")}>♙<span>Profile</span></button></nav>;
 const CardImage=({s}: {s:Species})=><img src={s.image_url?.startsWith("/img/") ? categoryImages[s.category] : s.image_url} alt={s.common_name}/>;
 if(page==="home") return <Phone><div className="brand">RimbaQuest</div><section className="hero"><span>LV. 1 JUNGLE SCOUT</span><h2>Welcome, Explorer!</h2><p>Every discovery helps protect<br/>our beautiful rainforest wildlife!</p><b>🌿</b></section><div className="stats"><Stat value={`${progress.found} / ${progress.total}`} label="Wildlife Discovered"/><Stat value={`${progress.xp}`} label="Explorer Points"/></div><Title>Begin Your Quest</Title><button className="quest" onClick={()=>go("category")}><i>1</i><div><strong>Record a Discovery</strong><small>Spot wildlife & log your sighting!</small></div></button><button className="quest" onClick={()=>go("collection")}><i>2</i><div><strong>View My Collection</strong><small>See your unlocked Wildlife Cards!</small></div></button><Title>Recent Captures</Title><div className="recent"><img src="/images/recent-marmoset.jpg" alt="Recent wildlife"/><div><b>Your next discovery awaits</b><small>Choose the animal you spotted</small></div></div><Bottom/></Phone>;
 if(page==="category") return <Phone><Header title="Record a Discovery"/><img className="photo" src="/images/marmoset.jpg" alt="Wildlife reference"/><p className="center subtle">Tap photo to enlarge</p><h2>Choose a Wildlife Category</h2><p className="subtle">What type of animal did you see?</p><div className="grid">{["Mammal","Bird","Butterfly","Reptile"].map(c=><button className="tile" key={c} onClick={()=>{setCategory(c);go("species")}}><img src={categoryImages[c]} alt=""/><b>{c}s</b></button>)}</div></Phone>;
 if(page==="species") { const list=all.filter(s=>s.category===category); return <Phone><Header title="Record a Discovery"/><img className="photo" src="/images/marmoset.jpg" alt="Wildlife reference"/><h2>Which {category.toLowerCase()} did you see?</h2><p className="subtle">Select the species that looks most like what you saw</p><div className="grid">{(list.length?list:fallback.filter(s=>s.category===category)).slice(0,8).map(s=><button className="species" key={s.id} onClick={()=>select(s)}><CardImage s={s}/><b>{s.common_name}</b><small>{s.category}</small></button>)}</div></Phone> }
 if(page==="confirm") return <Phone><Header title="Confirm Discovery"/><CardImage s={chosen}/><h2>{chosen.common_name} <em>{chosen.category}</em></h2><Info label="LOCATION" value="Kuala Lumpur, Malaysia"/><Info label="DATE & TIME" value={new Date().toLocaleDateString("en-MY",{day:"numeric",month:"short",year:"numeric"})}/><h3>Is this the species you saw?</h3><p className="subtle">Double-check the photo and details before you record your discovery.</p><button className="primary" onClick={confirm}>Yes, Record My Discovery!</button><button className="secondary" onClick={()=>go("species")}>Choose Another Species</button></Phone>;
 if(page==="success") return <Phone><div className="success"><p>Success!</p><h2>New Wildlife Discovered!</h2><span>Level 1 · Discovered</span><CardImage s={chosen}/><h3>{chosen.common_name}</h3><i>{chosen.scientific_name}</i><div className="two"><Info label="DATE RECORDED" value="Today"/><Info label="DISCOVERY STATUS" value="Confirmed"/></div><aside>+100 Explorer Experience Points</aside><button className="primary" onClick={()=>go("about")}>View My Card</button><button className="link" onClick={()=>go("category")}>Record Another Discovery</button></div></Phone>;
 if(page==="collection") return <Phone><Header title="My Collection" back={false}/><section className="progress"><div><b>{progress.found} / {progress.total}</b><small>Wildlife Discovered</small></div><span>LV. 1 TRACKER</span><meter min="0" max={Math.max(progress.total,1)} value={progress.found}/></section><div className="filters">{["All","Mammal","Bird","Butterfly","Reptile"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}s</button>)}</div><div className="grid">{items.slice(0,12).map(s=>discovered.includes(s.id)?<button className="species" key={s.id} onClick={()=>{setChosen(s);go("about")}}><CardImage s={s}/><b>{s.common_name}</b><small>{s.category}</small></button>:<button className="species locked" key={s.id} onClick={()=>{setChosen(s);go("locked")}}><div>🔒<small>UNDISCOVERED</small></div><b>Undiscovered</b><small>{s.category}</small></button>)}</div><Bottom/></Phone>;
 if(["about","facts","gallery"].includes(page)) return <Phone><Header title={chosen.common_name}/><div className="tabs">{(["about","facts","gallery"] as Page[]).map(t=><button className={tab===t?"active":""} onClick={()=>{setTab(t);go(t)}} key={t}>{t==="facts"?"Fun Facts":t[0].toUpperCase()+t.slice(1)}</button>)}</div>{tab==="about"&&<><div className="chips"><span>Level 1 · Discovered</span><span>{chosen.category}</span></div><Info label="SCIENTIFIC NAME" value={chosen.scientific_name}/>{chosen.act716_status&&<Info label="MALAYSIAN PROTECTION STATUS" value={chosen.act716_status}/>}<Info label="HABITAT" value={chosen.habitat}/><Info label="DIET" value={chosen.diet}/><Info label="ABOUT" value={`Learn about ${chosen.common_name} while observing wildlife safely from a respectful distance.`}/></>}{tab==="facts"&&<><section className="quiz"><b>QUIZ</b><h2>Test Your Knowledge!</h2><p>Take a quiz about {chosen.common_name} and earn XP!</p><button className="primary" onClick={()=>alert("Quiz interactions are not activated in this Iteration 1 build.")}>▶ Play Quiz</button></section><Title>Fun Facts</Title>{[chosen.fun_fact,"Wild animals need space and quiet to thrive.","Every careful observation can help us learn."].map(x=><p className="fact" key={x}>{x}</p>)}</>}{tab==="gallery"&&<div className="gallery">{["marmoset.jpg","common-marmoset-card.jpg","long-tailed-macaque-card.jpg","silvered-langur-card.jpg"].map(x=><img key={x} src={`/images/${x}`} alt={`${chosen.common_name} gallery`}/>)}</div>}</Phone>;
 if(page==="locked") return <Phone><Header title="Undiscovered"/><section className="lockcard"><CardImage s={chosen}/><h2>{chosen.common_name} <em>{chosen.category}</em></h2><i>{chosen.scientific_name}</i><p>{chosen.habitat}</p><Info label="DISCOVERY HINT" value="Keep exploring safely and observe from a distance to unlock this creature."/><aside>Keep exploring! Your first confirmed discovery unlocks this card.</aside></section></Phone>;
 return <Phone><Header title="My Progress"/><section className="progress"><small>OVERALL PROGRESS</small><h2>{progress.found} / {progress.total}</h2><b>{progress.total?Math.round(progress.found/progress.total*100):0}% Unlocked</b><meter min="0" max={Math.max(progress.total,1)} value={progress.found}/><div className="two"><Info label="EXPLORER POINTS" value={`${progress.xp} XP`}/><Info label="CURRENT LEVEL" value="LV. 1 Scout"/></div></section><Title>CATEGORY PROGRESS</Title>{progress.categories.map(x=><div className="row" key={x.category}><b>{x.category}s</b><span>{x.discovered} / {x.total} Found</span></div>)}<aside>Spot more wildlife to level up your scout status!</aside><Title>ACHIEVEMENTS UNLOCKED</Title><div className="chips"><span>🏅 First Discovery</span><span>🌱 Wildlife Friend</span></div><Bottom/></Phone>;
}
const Phone=({children}:{children:React.ReactNode})=><main className="phone">{children}</main>;
const Title=({children}:{children:React.ReactNode})=><h3 className="title">{children}</h3>;
const Stat=({value,label}:{value:string,label:string})=><div className="stat"><b>{value}</b><small>{label}</small></div>;
const Info=({label,value}:{label:string,value:string})=><div className="info"><small>{label}</small><b>{value}</b></div>;
