import { StyleSheet } from 'react-native';

export const battleStyles = StyleSheet.create({
  battleHero: { backgroundColor: '#FDF4E7', borderColor: '#F5DEB3', borderWidth: 1, borderRadius: 18, padding: 14, marginBottom: 14 },
  battleHeroTitle: { color: '#8A4B08', fontSize: 16, fontWeight: '900' },
  battleHeroCopy: { color: '#8A4B08', fontSize: 12, lineHeight: 17, marginTop: 4 },
  battleCardSelect: { width: '48%', borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 16, overflow: 'hidden', padding: 6, backgroundColor: '#FFFFFF' },
  battleCardSelectActive: { borderColor: '#0BA84A', borderWidth: 2 },
  battleCardImage: { width: '100%', height: 90, borderRadius: 10 },
  battleStatsRow: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 4, marginTop: 6 },
  hpBadge: { fontSize: 10, fontWeight: '800', color: '#D9383A', backgroundColor: '#FCE8E8', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, overflow: 'hidden' },
  atkBadge: { fontSize: 10, fontWeight: '800', color: '#B36200', backgroundColor: '#FFF2DF', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, overflow: 'hidden' },
  battleButtonSmall: { backgroundColor: '#0BA84A', borderRadius: 8, paddingVertical: 6, alignItems: 'center', marginTop: 6 },
  battleButtonSmallText: { color: '#FFFFFF', fontSize: 10, fontWeight: '800' },
  arenaOpponentBox: { borderWidth: 1, borderColor: '#F5C6CB', backgroundColor: '#FFF5F5', borderRadius: 16, padding: 14 },
  arenaPlayerBox: { borderWidth: 1, borderColor: '#CBECD6', backgroundColor: '#F4FFF7', borderRadius: 16, padding: 14 },
  arenaHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  arenaOpponentName: { color: '#8C1D24', fontSize: 15, fontWeight: '900' },
  arenaPlayerName: { color: '#087B35', fontSize: 15, fontWeight: '900' },
  arenaHpText: { fontSize: 12, fontWeight: '800', color: '#1B211C' },
  hpTrack: { height: 10, backgroundColor: '#E0E6E2', borderRadius: 5, overflow: 'hidden', marginTop: 8 },
  hpFillOpponent: { height: '100%', backgroundColor: '#D9383A' },
  hpFillPlayer: { height: '100%', backgroundColor: '#0BA84A' },
  arenaVsText: { textAlign: 'center', fontSize: 16, fontWeight: '900', color: '#879089', marginVertical: 8 },
  battleLogBox: { borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 14, padding: 12, marginVertical: 12, backgroundColor: '#FAFCFA', minHeight: 90 },
  battleLogTitle: { fontSize: 11, fontWeight: '900', color: '#566159', marginBottom: 6 },
  battleLogText: { fontSize: 11, color: '#273229', lineHeight: 16, marginTop: 2 },
  battleActions: { gap: 8 },
  lockedAbilityNotice: { borderWidth: 1, borderColor: '#E2E7E3', borderRadius: 10, padding: 8, alignItems: 'center', backgroundColor: '#F8FAF8' },
  lockedAbilityNoticeText: { fontSize: 10, color: '#7B857F', fontWeight: '700' },
  battleOutcomeBox: { borderWidth: 1, borderColor: '#CBECD6', backgroundColor: '#F4FFF7', borderRadius: 16, padding: 16, alignItems: 'center' },
  battleOutcomeTitle: { fontSize: 18, fontWeight: '900', color: '#087B35' },
  battleOutcomeCopy: { fontSize: 12, color: '#566159', textAlign: 'center', marginVertical: 8 },
  arenaCardImage: { width: '100%', height: 90, borderRadius: 10, marginBottom: 8 },
  battleButtonSmallIdle: { backgroundColor: '#879089' },
  battleOutcomeBoxLose: { borderColor: '#F5C6CB', backgroundColor: '#FFF5F5' },
  battleOutcomeTitleLose: { color: '#8C1D24' },
});
