import { StyleSheet } from 'react-native';

export const collectionStyles = StyleSheet.create({
  stats: { flexDirection: 'row', gap: 12, marginVertical: 16 },
  collectionCard: { flex: 1, minHeight: 165, borderColor: '#DFE7E1', borderWidth: 1, borderRadius: 16, overflow: 'hidden', paddingBottom: 8, backgroundColor: '#FFFFFF' },
  collectionGridRow: { gap: 12 },
  collectionGridContent: { gap: 12 },
  lockedSpeciesImage: { opacity: 0.28 },
  lockedOverlay: { position: 'absolute', top: 0, left: 0, right: 0, height: 96, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.2)' },
  lockIcon: { fontSize: 20 },
  lockedLabel: { color: '#68716C', fontSize: 9, fontWeight: '900', marginTop: 2 },
  tabs: { flexDirection: 'row', gap: 14, borderBottomWidth: 1, borderBottomColor: '#E2E7E3', marginBottom: 14 },
  tab: { paddingVertical: 9, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabActive: { borderBottomColor: '#0BA84A' },
  tabText: { color: '#6A736D', fontSize: 12, fontWeight: '700' },
  tabTextActive: { color: '#0BA84A', fontWeight: '900' },
  fact: { color: '#273229', fontSize: 12, lineHeight: 18, borderBottomWidth: 1, borderBottomColor: '#E6EAE7', paddingVertical: 10 },
  gallery: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  galleryImage: { width: '100%', height: 130, borderRadius: 12 },
  lockedDetail: { borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 20, padding: 14, backgroundColor: '#FFFFFF' },
  lockedImage: { width: '100%', height: 210, borderRadius: 14, opacity: 0.5 },
  lockedWarningBox: { borderWidth: 1, borderColor: '#F5C6CB', backgroundColor: '#FFF3CD', borderRadius: 12, padding: 12, marginTop: 12 },
  lockedWarningTitle: { color: '#856404', fontSize: 12, fontWeight: '800' },
  lockedWarningText: { color: '#856404', fontSize: 11, lineHeight: 16, marginTop: 4 },
  battleStatsContainer: { gap: 10 },
  battleStatHeader: { borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 16, padding: 14, backgroundColor: '#FFFFFF' },
  battleStatHeaderTitle: { fontSize: 14, fontWeight: '800', color: '#1B211C' },
  abilitySlotLocked: { flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#E1E8E3', borderRadius: 12, padding: 10, backgroundColor: '#F8FAF8', marginBottom: 6 },
  abilitySlotIcon: { fontSize: 16 },
  abilitySlotName: { fontSize: 12, fontWeight: '800', color: '#566159' },
  abilitySlotHint: { fontSize: 10, color: '#879089', marginTop: 2 },
  galleryEmpty: { borderWidth: 1, borderColor: '#CBECD6', backgroundColor: '#F4FFF7', borderRadius: 14, padding: 18, alignItems: 'center' },
  galleryEmptyTitle: { color: '#087B35', fontSize: 15, fontWeight: '800', marginBottom: 5 },
  galleryItem: { width: '48%' },
  galleryPlaceholder: { backgroundColor: '#E8EEEA' },
});
