import { StyleSheet } from 'react-native';

export const discoveryStyles = StyleSheet.create({
  heroImage: { width: 145, height: 145, borderRadius: 18, alignSelf: 'center', marginBottom: 6 },
  confirmImage: { width: 170, height: 170, borderRadius: 18, alignSelf: 'center', marginBottom: 14 },
  caption: { color: '#69716B', fontSize: 11, textAlign: 'center', marginBottom: 16 },
  categoryTile: { width: '48%', height: 145, borderRadius: 18, overflow: 'hidden', position: 'relative', backgroundColor: '#E4E8E5' },
  tileImage: { width: '100%', height: '100%' },
  tileShade: { position: 'absolute', left: 0, right: 0, bottom: 0, top: '40%', backgroundColor: 'rgba(0,0,0,0.5)' },
  tileLabel: { position: 'absolute', bottom: 14, left: 0, right: 0, textAlign: 'center', color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
  speciesCard: { width: '48%', minHeight: 165, borderColor: '#DFE7E1', borderWidth: 1, borderRadius: 16, overflow: 'hidden', paddingBottom: 8, backgroundColor: '#FFFFFF' },
  question: { color: '#1B211C', fontSize: 14, fontWeight: '800', marginTop: 16 },
  success: { alignItems: 'center', paddingTop: 20 },
  successSmall: { color: '#1B211C', fontSize: 16, fontWeight: '800' },
  successTitle: { color: '#0BA84A', fontSize: 22, fontWeight: '900', marginTop: 6 },
  unlockImage: { width: 125, height: 125, borderRadius: 16, marginVertical: 12 },
  xp: { alignSelf: 'stretch', color: '#087B35', borderWidth: 1, borderColor: '#CBECD6', backgroundColor: '#F4FFF7', borderRadius: 12, textAlign: 'center', fontSize: 13, fontWeight: '800', padding: 10, marginTop: 12 },
  cameraPage: { flex: 1, backgroundColor: '#182019', overflow: 'hidden' },
  cameraPermission: { flex: 1, padding: 24, justifyContent: 'center', alignItems: 'center', gap: 16, backgroundColor: '#182019' },
  cameraTitle: { color: '#FFFFFF', fontSize: 16, fontWeight: '800', textAlign: 'center', lineHeight: 24 },
  cameraPreview: { flex: 1 },
  cameraOverlay: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 25, justifyContent: 'flex-end', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.15)' },
  cameraBackButton: { position: 'absolute', top: 16, left: 16, width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0,0,0,0.52)', alignItems: 'center', justifyContent: 'center' },
  cameraBackText: { color: '#FFFFFF', fontSize: 28, lineHeight: 30, fontWeight: '700' },
  cameraBrand: { position: 'absolute', top: 26, color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  cameraHint: { position: 'absolute', top: 68, color: '#FFFFFF', backgroundColor: 'rgba(0,0,0,0.62)', borderRadius: 18, paddingHorizontal: 12, paddingVertical: 6, fontSize: 11, fontWeight: '700' },
  cameraActionsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%', paddingHorizontal: 10 },
  samplePhotoButton: { backgroundColor: 'rgba(255,255,255,0.25)', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 16 },
  samplePhotoText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  shutter: { width: 70, height: 70, borderRadius: 35, backgroundColor: 'rgba(255,255,255,0.82)', padding: 5, alignItems: 'center', justifyContent: 'center' },
  shutterInner: { width: '100%', height: '100%', borderRadius: 30, backgroundColor: '#FFFFFF', borderWidth: 2, borderColor: '#D9E2DB' },
  fullWidth: { alignSelf: 'stretch' },
  cameraError: { color: '#FFFFFF', backgroundColor: 'rgba(217,56,58,0.85)', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8, fontSize: 12, fontWeight: '700', textAlign: 'center', marginBottom: 12 },
  locationModeRow: { flexDirection: 'row', gap: 8, marginTop: 8, marginBottom: 8 },
  locationModeChip: { flex: 1, borderWidth: 1, borderColor: '#C8D1CA', borderRadius: 12, paddingVertical: 10, alignItems: 'center', backgroundColor: '#FFFFFF' },
  locationModeChipActive: { borderColor: '#0BA84A', backgroundColor: '#EDF5EF' },
  locationModeText: { fontSize: 11, fontWeight: '800', color: '#68716C', textAlign: 'center' },
  locationModeTextActive: { color: '#087B35' },
  photoModal: { flex: 1, backgroundColor: 'rgba(0,0,0,0.88)', alignItems: 'center', justifyContent: 'center', padding: 16 },
  photoModalBackdrop: { width: '100%', alignItems: 'center' },
  photoModalImage: { width: '100%', height: 420 },
  photoModalHint: { color: '#FFFFFF', marginTop: 12, fontWeight: '700' },
  cameraPersonalRecord: { color: '#FFFFFF', backgroundColor: 'rgba(0,0,0,0.62)', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5, fontSize: 10, textAlign: 'center', overflow: 'hidden', marginBottom: 16 },
});
