import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  homeRoot: { flex: 1 },
  homeBackground: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  decoCircle1: { position: 'absolute', left: -50, top: -50, width: 180, height: 180, borderRadius: 90, backgroundColor: '#78B833', opacity: 0.15 },
  decoCircle2: { position: 'absolute', left: '68%', top: 50, width: 140, height: 140, borderRadius: 70, backgroundColor: '#A8D860', opacity: 0.1 },
  decoCircle3: { position: 'absolute', left: -20, top: 700, width: 120, height: 120, borderRadius: 60, backgroundColor: '#FFC314', opacity: 0.07 },
  decoCircle4: { position: 'absolute', left: '74%', top: 500, width: 100, height: 100, borderRadius: 50, backgroundColor: '#78B833', opacity: 0.06 },
  homeScroll: { paddingHorizontal: 20, gap: 20 },
  brandHeader: { alignItems: 'flex-start' },
  brandLogo: { width: 225, height: 50 },
  profileCardWrap: { position: 'relative' },
  profileCard: { borderRadius: 28, padding: 18, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 10, elevation: 3 },
  leafDecorFloat: { position: 'absolute', top: -38, right: -9, width: 103, height: 54, zIndex: 2 },
  profileCardGradient: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  profileRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  avatarFrame: { width: 64, height: 64, borderRadius: 32, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  avatarInner: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#D8EDD8', alignItems: 'center', justifyContent: 'center' },
  avatarImageLarge: { width: 56, height: 56, borderRadius: 28 },
  profileInfo: { flex: 1, gap: 6 },
  levelBadge: { alignSelf: 'flex-start', borderRadius: 12, overflow: 'hidden' },
  levelBadgeGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  levelBadgeText: { color: '#0A4D26', fontSize: 11, fontWeight: '800' },
  profileName: { color: '#0A4D26', fontSize: 23, fontWeight: '900' },
  profileSubtitle: { color: '#2D7A4E', fontSize: 12, fontWeight: '500' },
  menuSection: { gap: 12 },
  sectionHeading: { color: '#0A4D26', fontSize: 20, fontWeight: '900' },
  collectionTileWrap: { position: 'relative' },
  collectionTile: { flexDirection: 'row', alignItems: 'center', gap: 14, borderRadius: 24, padding: 16, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 10, elevation: 3 },
  pandaDecorFloat: { position: 'absolute', top: -43, right: 10, width: 135, height: 45, zIndex: 2 },
  collectionTileGradient: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  collectionBookImage: { width: 84, height: 57, borderRadius: 16 },
  collectionContent: { flex: 1, gap: 8 },
  collectionHeader: { gap: 2 },
  collectionTitle: { color: '#0A4D26', fontSize: 16, fontWeight: '900' },
  collectionSubtitle: { color: '#2D7A4E', fontSize: 12, fontWeight: '500' },
  collectionProgress: { gap: 6 },
  collectionProgressRow: { flexDirection: 'row', justifyContent: 'space-between' },
  collectionProgressText: { color: '#2D7A4E', fontSize: 11, fontWeight: '700' },
  collectionProgressPercent: { color: '#0A4D26', fontSize: 11, fontWeight: '700' },
  progressTrackSm: { height: 8, borderRadius: 4, backgroundColor: '#D8EDD8', overflow: 'hidden' },
  progressFillSm: { height: '100%', borderRadius: 4, backgroundColor: '#78B833' },
  tileRow: { flexDirection: 'row', gap: 12 },
  actionTile: { flex: 1, borderRadius: 24, alignItems: 'center', justifyContent: 'center', paddingVertical: 16, gap: 10, minHeight: 120, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 10, elevation: 3 },
  actionTileGradient: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  actionTileIcon: { width: 68, height: 48 },
  actionTileLabel: { color: '#0A4D26', fontSize: 15, fontWeight: '800' },
  continueSection: { gap: 12 },
  continueHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  seeAllOrange: { color: '#E8541A', fontSize: 13, fontWeight: '700' },
  seeAllTap: { paddingVertical: 4, paddingHorizontal: 4 },
  learnCard: { flexDirection: 'row', alignItems: 'center', borderRadius: 24, padding: 14, gap: 12, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.08, shadowRadius: 10, elevation: 2 },
  learnCardGradient: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  learnThumb: { width: 58, height: 58, borderRadius: 18 },
  learnInfo: { flex: 1, gap: 6 },
  learnName: { color: '#0A4D26', fontSize: 15, fontWeight: '800' },
  learnMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  learnCategoryPill: { borderRadius: 10, overflow: 'hidden' },
  learnCategoryPillGradient: { paddingHorizontal: 10, paddingVertical: 3 },
  learnCategoryText: { color: '#0A4D26', fontSize: 11, fontWeight: '700' },
  learnLocationText: { color: '#2D7A4E', fontSize: 11, fontWeight: '500', flexShrink: 1 },
  learnProgressTrack: { height: 7, borderRadius: 4, backgroundColor: '#D8EDD8', overflow: 'hidden' },
  learnProgressFill: { height: '100%', borderRadius: 4, backgroundColor: '#78B833' },
  learnEmpty: { borderRadius: 24, padding: 18, alignItems: 'center', backgroundColor: '#FFFFFF' },
});
