import { StyleSheet } from 'react-native';

// Login screen (Figma node 302:97).
export const loginStyles = StyleSheet.create({
  loginRoot: { flex: 1 },
  loginBackground: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  loginDecoCircle1: { position: 'absolute', left: -60, top: -60, width: 200, height: 200, borderRadius: 100, backgroundColor: '#78B833', opacity: 0.15 },
  loginDecoCircle2: { position: 'absolute', left: '77%', top: '82%', width: 140, height: 140, borderRadius: 70, backgroundColor: '#78B833', opacity: 0.12 },
  loginScroll: { flexGrow: 1, paddingHorizontal: 24, paddingBottom: 40 },
  loginCenterWrap: { flex: 1, justifyContent: 'center' },
  loginContent: { alignItems: 'center', gap: 24, paddingVertical: 16 },
  loginMascotBlob: { width: 180, height: 180, borderRadius: 90, backgroundColor: 'rgba(216,240,224,0.4)', alignItems: 'center', justifyContent: 'center' },
  loginMascotImage: { width: 176, height: 180 },
  loginTitle: { color: '#0A4D26', fontSize: 24, lineHeight: 29, fontWeight: '900', textAlign: 'center' },
  loginFields: { gap: 14, width: '100%' },
  loginInputBox: { flexDirection: 'row', alignItems: 'center', gap: 12, height: 52, borderRadius: 16, borderWidth: 1.5, borderColor: '#D1E8D5', backgroundColor: 'rgba(255,255,255,0.93)', paddingHorizontal: 16 },
  loginInputBoxError: { borderColor: '#D9383A', backgroundColor: '#FFF6F6' },
  loginInput: { flex: 1, color: '#0A4D26', fontSize: 15, fontWeight: '500', paddingVertical: 0 },
  loginEyeToggle: { padding: 2 },
  loginFieldError: { color: '#D9383A', fontSize: 11, fontWeight: '700', marginTop: -6, marginLeft: 4 },
  loginForgotRow: { alignItems: 'flex-end', width: '100%' },
  loginForgotText: { color: '#2EB85C', fontSize: 14, fontWeight: '700' },
  loginActions: { gap: 16, alignItems: 'center', width: '100%' },
  loginSubmitBtn: { height: 52, width: '100%', borderRadius: 100, backgroundColor: '#0A4D26', alignItems: 'center', justifyContent: 'center' },
  loginSubmitBtnText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
  loginSignupRow: { alignItems: 'center', gap: 4 },
  loginSignupText: { color: '#637D6E', fontSize: 14 },
  loginSignupLink: { color: '#0A4D26', fontSize: 14, fontWeight: '700' },
  loginErrorBanner: { color: '#D9383A', backgroundColor: '#FCE8E8', borderRadius: 10, padding: 10, fontSize: 12, fontWeight: '700', width: '100%', textAlign: 'center' },
});
