import { StyleSheet } from 'react-native';

export const styles: any = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#FFFFFF' },
  page: { flex: 1, alignSelf: 'center', width: '100%', maxWidth: 520, backgroundColor: '#FFFFFF' },
  content: { paddingHorizontal: 18, paddingTop: 8, paddingBottom: 110 },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16 },
  topBrandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginVertical: 14 },
  brand: { fontSize: 24, fontWeight: '900', color: '#182019' },
  avatarPill: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#EDF5EF', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 6, gap: 6 },
  avatarEmoji: { fontSize: 18 },
  avatarName: { fontSize: 12, fontWeight: '800', color: '#087B35' },
  notice: { color: '#8B5D00', backgroundColor: '#FFF7DD', borderRadius: 10, padding: 10, fontSize: 12, marginBottom: 10 },
  hero: { minHeight: 155, borderColor: '#DFE7E1', borderWidth: 1, borderRadius: 22, padding: 18, position: 'relative', overflow: 'hidden', backgroundColor: '#FAFCFA' },
  level: { alignSelf: 'flex-start', overflow: 'hidden', color: '#087B35', backgroundColor: '#DFF6E7', fontSize: 10, fontWeight: '800', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20 },
  heroTitle: { color: '#1B211C', fontSize: 26, lineHeight: 30, fontWeight: '900', marginTop: 10 },
  heroCopy: { color: '#66706A', fontSize: 13, lineHeight: 20, marginTop: 8 },
  mascot: { position: 'absolute', right: 14, bottom: 14, fontSize: 44 },
  stats: { flexDirection: 'row', gap: 12, marginVertical: 16 },
  stat: { flex: 1, borderColor: '#DFE7E1', borderWidth: 1, borderRadius: 18, padding: 14, backgroundColor: '#FFFFFF' },
  statValue: { color: '#0BA84A', fontSize: 22, fontWeight: '900' },
  statLabel: { color: '#66706A', fontSize: 11, marginTop: 4, fontWeight: '700' },
  section: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 14, marginBottom: 8 },
  sectionTitle: { fontSize: 15, fontWeight: '800', color: '#1B211C' },
  seeAll: { color: '#0BA84A', fontSize: 12, fontWeight: '700' },
  quest: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F0F4F1' },
  questNumber: { width: 32, height: 32, lineHeight: 32, textAlign: 'center', color: '#FFFFFF', backgroundColor: '#35B85E', borderRadius: 16, fontWeight: '900' },
  cardTitle: { color: '#1B211C', fontSize: 14, fontWeight: '800', marginTop: 6, paddingHorizontal: 6 },
  muted: { color: '#707872', fontSize: 11, marginTop: 2, paddingHorizontal: 6 },
  recentGrid: { gap: 10, marginTop: 6 },
  recentItem: { borderColor: '#DFE7E1', borderWidth: 1, borderRadius: 14, overflow: 'hidden', flexDirection: 'row', alignItems: 'center', padding: 8, backgroundColor: '#FFFFFF' },
  recentImage: { width: 70, height: 70, borderRadius: 10 },
  recentCopy: { marginLeft: 12, flex: 1 },
  recentEmpty: { borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 14, padding: 18, alignItems: 'center', backgroundColor: '#FAFCFA' },
  header: { height: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  headerTitle: { fontSize: 18, fontWeight: '800', color: '#1B211C', flex: 1, textAlign: 'center' },
  back: { width: 38, height: 38, borderRadius: 19, borderWidth: 1, borderColor: '#DFE7E1', alignItems: 'center', justifyContent: 'center' },
  backSpacer: { width: 38 },
  backText: { fontSize: 30, color: '#1B211C', lineHeight: 32 },
  heroImage: { width: 145, height: 145, borderRadius: 18, alignSelf: 'center', marginBottom: 6 },
  confirmImage: { width: 170, height: 170, borderRadius: 18, alignSelf: 'center', marginBottom: 14 },
  caption: { color: '#69716B', fontSize: 11, textAlign: 'center', marginBottom: 16 },
  pageTitle: { color: '#1B211C', fontSize: 22, lineHeight: 26, fontWeight: '900', marginTop: 4 },
  subTitle: { color: '#68716C', fontSize: 13, lineHeight: 18, marginTop: 6, marginBottom: 14 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  categoryTile: { width: '48%', height: 145, borderRadius: 18, overflow: 'hidden', position: 'relative', backgroundColor: '#E4E8E5' },
  tileImage: { width: '100%', height: '100%' },
  tileShade: { position: 'absolute', left: 0, right: 0, bottom: 0, top: '40%', backgroundColor: 'rgba(0,0,0,0.5)' },
  tileLabel: { position: 'absolute', bottom: 14, left: 0, right: 0, textAlign: 'center', color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
  speciesCard: { width: '48%', minHeight: 165, borderColor: '#DFE7E1', borderWidth: 1, borderRadius: 16, overflow: 'hidden', paddingBottom: 8, backgroundColor: '#FFFFFF' },
  speciesImage: { width: '100%', height: 96 },
  cardBottomRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 6, marginTop: 4 },
  categoryText: { color: '#0BA84A', fontSize: 10, fontWeight: '700' },
  hpBadgeMini: { color: '#D9383A', fontSize: 10, fontWeight: '800' },
  lockedSpeciesImage: { opacity: 0.28 },
  lockedOverlay: { position: 'absolute', top: 0, left: 0, right: 0, height: 96, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.2)' },
  lockIcon: { fontSize: 20 },
  lockedLabel: { color: '#68716C', fontSize: 9, fontWeight: '900', marginTop: 2 },
  categoryPill: { fontSize: 10, color: '#087B35', backgroundColor: '#DFF6E7', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10, overflow: 'hidden', alignSelf: 'flex-start' },
  info: { borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 14, padding: 12, marginTop: 10, backgroundColor: '#FFFFFF' },
  infoLabel: { color: '#78817B', fontSize: 9, fontWeight: '900', letterSpacing: 0.4 },
  infoValue: { color: '#1B211C', fontSize: 12, lineHeight: 18, fontWeight: '700', marginTop: 4 },
  inputGroup: { marginTop: 12 },
  inputLabel: { color: '#566159', fontSize: 10, fontWeight: '800', marginBottom: 5 },
  textInput: { borderWidth: 1, borderColor: '#C8D1CA', borderRadius: 12, paddingHorizontal: 12, minHeight: 44, fontSize: 14, color: '#1B211C', backgroundColor: '#FFFFFF' },
  question: { color: '#1B211C', fontSize: 14, fontWeight: '800', marginTop: 16 },
  primary: { minHeight: 48, marginTop: 14, borderRadius: 24, backgroundColor: '#0BA84A', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  primaryText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' },
  secondary: { minHeight: 46, marginTop: 9, borderRadius: 23, backgroundColor: '#FFFFFF', borderColor: '#C8D1CA', borderWidth: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 },
  secondaryText: { color: '#1B211C', fontSize: 13, fontWeight: '700' },
  success: { alignItems: 'center', paddingTop: 20 },
  successSmall: { color: '#1B211C', fontSize: 16, fontWeight: '800' },
  successTitle: { color: '#0BA84A', fontSize: 22, fontWeight: '900', marginTop: 6 },
  unlockImage: { width: 125, height: 125, borderRadius: 16, marginVertical: 12 },
  scientific: { color: '#68716C', fontStyle: 'italic', fontSize: 12, marginTop: 3 },
  infoPair: { flexDirection: 'row', alignSelf: 'stretch', gap: 8, marginTop: 6 },
  xp: { alignSelf: 'stretch', color: '#087B35', borderWidth: 1, borderColor: '#CBECD6', backgroundColor: '#F4FFF7', borderRadius: 12, textAlign: 'center', fontSize: 13, fontWeight: '800', padding: 10, marginTop: 12 },
  textButton: { paddingVertical: 12, alignItems: 'center' },
  textButtonText: { color: '#0BA84A', fontWeight: '800', fontSize: 13 },
  progressCard: { borderColor: '#DFE7E1', borderWidth: 1, borderRadius: 16, padding: 14, marginBottom: 12, backgroundColor: '#FFFFFF' },
  progressTop: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  progressValue: { fontSize: 22, color: '#1B211C', fontWeight: '900', marginTop: 3 },
  unlocked: { color: '#0BA84A', fontSize: 12, fontWeight: '800' },
  track: { height: 8, backgroundColor: '#E8EEEA', borderRadius: 4, overflow: 'hidden', marginTop: 12 },
  fill: { height: '100%', backgroundColor: '#0BA84A', borderRadius: 4 },
  chips: { gap: 8, paddingBottom: 12 },
  chip: { borderRadius: 16, backgroundColor: '#F0F4F1', paddingHorizontal: 12, paddingVertical: 7 },
  chipActive: { backgroundColor: '#0BA84A' },
  chipText: { fontSize: 11, color: '#607068', fontWeight: '700' },
  chipTextActive: { color: '#FFFFFF' },
  tabs: { flexDirection: 'row', gap: 14, borderBottomWidth: 1, borderBottomColor: '#E2E7E3', marginBottom: 14 },
  tab: { paddingVertical: 9, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabActive: { borderBottomColor: '#0BA84A' },
  tabText: { color: '#6A736D', fontSize: 12, fontWeight: '700' },
  tabTextActive: { color: '#0BA84A', fontWeight: '900' },
  badges: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 6 },
  badge: { color: '#31613F', backgroundColor: '#EDF5EF', borderRadius: 14, fontSize: 10, fontWeight: '700', paddingHorizontal: 10, paddingVertical: 6, overflow: 'hidden' },
  quiz: { borderColor: '#CBECD6', borderWidth: 1, backgroundColor: '#F4FFF7', borderRadius: 16, padding: 14 },
  quizLabel: { color: '#087B35', fontSize: 10, fontWeight: '800' },
  quizTitle: { fontSize: 17, color: '#1B211C', fontWeight: '800', marginTop: 4 },
  quizButton: { backgroundColor: '#0BA84A', alignSelf: 'flex-start', borderRadius: 16, marginTop: 12, paddingVertical: 8, paddingHorizontal: 14 },
  fact: { color: '#273229', fontSize: 12, lineHeight: 18, borderBottomWidth: 1, borderBottomColor: '#E6EAE7', paddingVertical: 10 },
  gallery: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  galleryImage: { width: '48%', height: 130, borderRadius: 12 },
  lockedDetail: { borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 20, padding: 14, backgroundColor: '#FFFFFF' },
  lockedImage: { width: '100%', height: 210, borderRadius: 14, opacity: 0.5 },
  lockedWarningBox: { borderWidth: 1, borderColor: '#F5C6CB', backgroundColor: '#FFF3CD', borderRadius: 12, padding: 12, marginTop: 12 },
  lockedWarningTitle: { color: '#856404', fontSize: 12, fontWeight: '800' },
  lockedWarningText: { color: '#856404', fontSize: 11, lineHeight: 16, marginTop: 4 },
  hint: { color: '#117B3A', backgroundColor: '#F0FAF3', borderColor: '#CBECD6', borderWidth: 1, borderRadius: 10, fontSize: 11, lineHeight: 16, padding: 10, marginTop: 12 },
  progressRow: { borderColor: '#DFE7E1', borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, backgroundColor: '#FFFFFF' },
  
  // Locations Styling
  disclaimerBox: { borderWidth: 1, borderColor: '#BEE5EB', backgroundColor: '#E2F0D9', borderRadius: 14, padding: 12, marginBottom: 12 },
  disclaimerTitle: { color: '#1E4620', fontSize: 12, fontWeight: '800' },
  disclaimerText: { color: '#2C5E2E', fontSize: 11, lineHeight: 16, marginTop: 3 },
  locationList: { gap: 12 },
  locationCard: { borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 16, padding: 14, backgroundColor: '#FFFFFF' },
  locationTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  locationName: { color: '#1B211C', fontSize: 15, fontWeight: '800', flex: 1 },
  distanceBadge: { color: '#0BA84A', backgroundColor: '#EAF8EF', borderRadius: 10, fontSize: 10, fontWeight: '800', paddingHorizontal: 8, paddingVertical: 3, overflow: 'hidden' },
  locationArea: { color: '#68716C', fontSize: 11, fontWeight: '700', marginTop: 3 },
  locationDesc: { color: '#525B55', fontSize: 12, lineHeight: 17, marginTop: 6 },
  wildlifeTagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginTop: 8, alignItems: 'center' },
  wildlifeTagLabel: { fontSize: 10, color: '#7B857F', fontWeight: '800' },
  wildlifeTagValue: { fontSize: 10, color: '#087B35', fontWeight: '700' },
  locationCardBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#F0F4F1' },
  bestTimeText: { fontSize: 10, color: '#7B857F' },
  viewDetailText: { fontSize: 11, color: '#0BA84A', fontWeight: '800' },
  locationDetailHero: { backgroundColor: '#F4FAF6', padding: 16, borderRadius: 16, marginBottom: 12, alignItems: 'center' },
  locationAreaHero: { fontSize: 14, fontWeight: '800', color: '#1B211C' },
  locationTypeBadge: { fontSize: 11, color: '#0BA84A', fontWeight: '700', marginTop: 4 },

  // Battle Styling
  battleHero: { backgroundColor: '#FDF4E7', borderColor: '#F5DEB3', borderWidth: 1, borderRadius: 18, padding: 14, marginBottom: 14 },
  battleHeroTitle: { color: '#8A4B08', fontSize: 16, fontWeight: '900' },
  battleHeroCopy: { color: '#8A4B08', fontSize: 12, lineHeight: 17, marginTop: 4 },
  battleCardSelect: { width: '48%', borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 16, overflow: 'hidden', padding: 6, backgroundColor: '#FFFFFF' },
  battleCardSelectActive: { borderColor: '#0BA84A', borderWidth: 2 },
  battleCardImage: { width: '100%', height: 90, borderRadius: 10 },
  battleStatsRow: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 4, marginTop: 6 },
  hpBadge: { fontSize: 10, fontWeight: '800', color: '#D9383A', backgroundColor: '#FCE8E8', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, overflow: 'hidden' },
  atkBadge: { fontSize: 10, fontWeight: '800', color: '#B36200', backgroundColor: '#FFF2DF', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, overflow: 'hidden' },
  battleButtonSmall: { backgroundColor: '#0BA84A', borderRadius: 8, paddingVertical: 6, alignItems: 'center', marginTop: 6 },
  battleButtonSmallText: { color: '#FFFFFF', fontSize: 10, fontWeight: '800' },

  // Battle Arena Styling
  arenaOpponentBox: { borderWidth: 1, borderColor: '#F5C6CB', backgroundColor: '#FFF5F5', borderRadius: 16, padding: 14 },
  arenaPlayerBox: { borderWidth: 1, borderColor: '#CBECD6', backgroundColor: '#F4FFF7', borderRadius: 16, padding: 14 },
  arenaHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  arenaOpponentName: { color: '#8C1D24', fontSize: 15, fontWeight: '900' },
  arenaPlayerName: { color: '#087B35', fontSize: 15, fontWeight: '900' },
  arenaHpText: { fontSize: 12, fontWeight: '800', color: '#1B211C' },
  hpTrack: { height: 10, backgroundColor: '#E0E6E2', borderRadius: 5, overflow: 'hidden', marginTop: 8 },
  hpFillOpponent: { height: '100%', backgroundColor: '#D9383A' },
  hpFillPlayer: { height: '100%', backgroundColor: '#0BA84A' },
  arenaVsText: { textAlign: 'center', fontSize: 16, fontWeight: '900', color: '#879089', marginVertical: 8 },
  battleLogBox: { borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 14, padding: 12, marginVertical: 12, backgroundColor: '#FAFCFA', minHeight: 90 },
  battleLogTitle: { fontSize: 11, fontWeight: '900', color: '#566159', marginBottom: 6 },
  battleLogText: { fontSize: 11, color: '#273229', lineHeight: 16, marginTop: 2 },
  battleActions: { gap: 8 },
  lockedAbilityNotice: { borderWidth: 1, borderColor: '#E2E7E3', borderRadius: 10, padding: 8, alignItems: 'center', backgroundColor: '#F8FAF8' },
  lockedAbilityNoticeText: { fontSize: 10, color: '#7B857F', fontWeight: '700' },
  battleOutcomeBox: { borderWidth: 1, borderColor: '#CBECD6', backgroundColor: '#F4FFF7', borderRadius: 16, padding: 16, alignItems: 'center' },
  battleOutcomeTitle: { fontSize: 18, fontWeight: '900', color: '#087B35' },
  battleOutcomeCopy: { fontSize: 12, color: '#566159', textAlign: 'center', marginVertical: 8 },
  buttonDisabled: { opacity: 0.5 },

  // Battle Stats Tab
  battleStatsContainer: { gap: 10 },
  battleStatHeader: { borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 16, padding: 14, backgroundColor: '#FFFFFF' },
  battleStatHeaderTitle: { fontSize: 14, fontWeight: '800', color: '#1B211C' },
  abilitySlotLocked: { flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#E1E8E3', borderRadius: 12, padding: 10, backgroundColor: '#F8FAF8', marginBottom: 6 },
  abilitySlotIcon: { fontSize: 16 },
  abilitySlotName: { fontSize: 12, fontWeight: '800', color: '#566159' },
  abilitySlotHint: { fontSize: 10, color: '#879089', marginTop: 2 },

  // Auth Styling
  authTabRow: { flexDirection: 'row', borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 14, overflow: 'hidden', marginBottom: 14 },
  authTab: { flex: 1, paddingVertical: 10, alignItems: 'center', backgroundColor: '#F8FAF8' },
  authTabActive: { backgroundColor: '#0BA84A' },
  authTabText: { fontSize: 13, fontWeight: '700', color: '#68716C' },
  authTabTextActive: { color: '#FFFFFF', fontWeight: '900' },
  authError: { color: '#D9383A', backgroundColor: '#FCE8E8', borderRadius: 10, padding: 10, fontSize: 12, fontWeight: '700', marginBottom: 12 },
  authForm: { gap: 10 },
  avatarPicker: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginVertical: 6 },
  avatarChoice: { width: '30%', borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 12, padding: 8, alignItems: 'center', backgroundColor: '#FFFFFF' },
  avatarChoiceActive: { borderColor: '#0BA84A', borderWidth: 2, backgroundColor: '#EDF5EF' },
  avatarChoiceEmoji: { fontSize: 24 },
  avatarChoiceName: { fontSize: 10, fontWeight: '800', color: '#566159', textTransform: 'capitalize', marginTop: 2 },

  // Profile Hero
  profileHero: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#DFE7E1', borderRadius: 18, padding: 14, marginBottom: 12, backgroundColor: '#FFFFFF' },
  profileHeroAvatar: { fontSize: 36, marginRight: 12 },
  profileHeroInfo: { flex: 1 },
  profileHeroName: { fontSize: 17, fontWeight: '900', color: '#1B211C' },
  profileHeroBand: { fontSize: 11, color: '#68716C', marginTop: 2 },
  editProfileBtn: { borderWidth: 1, borderColor: '#0BA84A', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 6 },
  editProfileBtnText: { color: '#0BA84A', fontSize: 11, fontWeight: '800' },

  // Camera Styles
  cameraPage: { flex: 1, backgroundColor: '#182019', overflow: 'hidden' },
  cameraPermission: { flex: 1, padding: 24, justifyContent: 'center', alignItems: 'center', gap: 16, backgroundColor: '#182019' },
  cameraTitle: { color: '#FFFFFF', fontSize: 16, fontWeight: '800', textAlign: 'center', lineHeight: 24 },
  cameraPreview: { flex: 1 },
  cameraOverlay: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 25, justifyContent: 'flex-end', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.15)' },
  cameraBackButton: { position: 'absolute', top: 16, left: 16, width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(0,0,0,0.52)', alignItems: 'center', justifyContent: 'center' },
  cameraBackText: { color: '#FFFFFF', fontSize: 28, lineHeight: 30, fontWeight: '700' },
  cameraBrand: { position: 'absolute', top: 26, color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  cameraHint: { position: 'absolute', top: 68, color: '#FFFFFF', backgroundColor: 'rgba(0,0,0,0.62)', borderRadius: 18, paddingHorizontal: 12, paddingVertical: 6, fontSize: 11, fontWeight: '700' },
  cameraPersonalRecord: { color: '#FFFFFF', backgroundColor: 'rgba(0,0,0,0.62)', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5, fontSize: 10, textAlign: 'center', overflow: 'hidden', marginBottom: 16 },
  cameraActionsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%', paddingHorizontal: 10 },
  samplePhotoButton: { backgroundColor: 'rgba(255,255,255,0.25)', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 16 },
  samplePhotoText: { color: '#FFFFFF', fontSize: 11, fontWeight: '800' },
  shutter: { width: 70, height: 70, borderRadius: 35, backgroundColor: 'rgba(255,255,255,0.82)', padding: 5, alignItems: 'center', justifyContent: 'center' },
  shutterInner: { width: '100%', height: '100%', borderRadius: 30, backgroundColor: '#FFFFFF', borderWidth: 2, borderColor: '#D9E2DB' },

  // Bottom Nav
  bottomNav: { position: 'absolute', height: 68, bottom: 0, left: 0, right: 0, backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E1E7E2', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  navItem: { width: 50, alignItems: 'center', justifyContent: 'center', minHeight: 46 },
  navIcon: { color: '#879089', fontSize: 17 },
  navLabel: { color: '#879089', fontSize: 9, marginTop: 2 },
  navActive: { color: '#0BA84A', fontWeight: '900' },
  navDisabled: { color: '#B9C1BC' },
  recordButton: { width: 52, height: 52, borderRadius: 26, backgroundColor: '#0BA84A', alignItems: 'center', justifyContent: 'center', marginTop: -24, shadowColor: '#0BA84A', shadowOpacity: 0.3, shadowRadius: 8, elevation: 5 },
  cameraNavIcon: { width: 24, height: 18, borderRadius: 4, borderWidth: 2, borderColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  cameraNavLens: { width: 8, height: 8, borderRadius: 4, borderWidth: 2, borderColor: '#FFFFFF' },
  fullWidth: { alignSelf: 'stretch' },
  quizOption: { minHeight: 52, paddingHorizontal: 14, paddingVertical: 10 },
  quizOptionSelected: { backgroundColor: '#0BA84A', borderColor: '#0BA84A' },
  quizOptionText: { textAlign: 'center', lineHeight: 18 },
  quizOptionTextSelected: { color: '#FFFFFF' },
  pressed: { opacity: 0.72 },
  galleryEmpty: { borderWidth: 1, borderColor: '#CBECD6', backgroundColor: '#F4FFF7', borderRadius: 14, padding: 18, alignItems: 'center' },
  galleryEmptyTitle: { color: '#087B35', fontSize: 15, fontWeight: '800', marginBottom: 5 },
  searchBox: { minHeight: 46, marginBottom: 12, borderWidth: 1, borderColor: '#C8D1CA', borderRadius: 12, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF' },
  searchIcon: { color: '#879089', fontSize: 18, marginRight: 8 },
  searchInput: { flex: 1, color: '#1B211C', fontSize: 13, minHeight: 44, paddingVertical: 0 },
  searchClear: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#EDF5EF', alignItems: 'center', justifyContent: 'center' },
  searchClearText: { color: '#087B35', fontSize: 20, lineHeight: 22, fontWeight: '700' },
  searchEmpty: { borderWidth: 1, borderColor: '#CBECD6', backgroundColor: '#F4FFF7', borderRadius: 14, padding: 18, alignItems: 'center' },
  searchEmptyTitle: { color: '#087B35', fontSize: 15, fontWeight: '800', marginBottom: 4 },
});
