"""Complete Iteration 1 species learning data and quiz records.

The script uses the curated batch notes, when present, then fills any remaining
empty fields with safe category-appropriate learning copy.  It updates both the
working SQLite database and the SQL seed used by a fresh Render disk.
"""

from __future__ import annotations

import json
import re
import sqlite3
from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
DB_FILE = REPO / "backend" / "data" / "RimbaQuest.db"
SEED_FILE = REPO / "backend" / "data" / "seed.sql"
NOTES_FILE = Path(__file__).with_name("generated_seed.txt")
START = "-- BEGIN complete Iteration 1 learning data"
END = "-- END complete Iteration 1 learning data"


def quote(value: str | None) -> str:
    return "NULL" if value is None else "'" + value.replace("'", "''") + "'"


def curated_notes() -> dict[str, dict[str, str]]:
    if not NOTES_FILE.exists():
        return {}
    return {
        item["id"]: item
        for line in NOTES_FILE.read_text(encoding="utf-8").splitlines()
        if line.strip()
        for item in [json.loads(line.rstrip(","))]
    }


def defaults(name: str, category: str) -> dict[str, str]:
    shared = {
        "threats": "Habitat loss, fragmentation and disturbance can affect this species.",
        "conservation_status": "Use current local conservation guidance when observing this species.",
        "responsible_observation": "Observe quietly from a respectful distance; never feed, touch or chase wildlife.",
        "distinctive_features": f"Compare the {name} carefully with the reference image, noting its shape, colours and behaviour.",
    }
    category_copy = {
        "Bird": {
            "habitat": "Forests, forest edges and other suitable Malaysian natural habitats.",
            "diet": "A natural mix of insects, fruit, seeds and other food available in its habitat.",
            "fun_fact": f"{name} is part of Malaysia’s diverse bird life and helps keep forest ecosystems connected.",
        },
        "Mammal": {
            "habitat": "Malaysian forests and other suitable natural habitats with cover and food.",
            "diet": "A natural diet of plant material, fruit, insects or small animals depending on the season.",
            "fun_fact": f"{name} has adaptations that help it find food and shelter in its forest habitat.",
        },
        "Reptile": {
            "habitat": "Forests, wetlands or other warm natural habitats in Malaysia.",
            "diet": "Food available in its habitat, such as insects, plants or small animals.",
            "fun_fact": f"{name} is an important part of the food web in its habitat.",
        },
        "Butterfly": {
            "habitat": "Gardens, forest edges and flowering natural habitats in Malaysia.",
            "diet": "Flower nectar as an adult, with caterpillars feeding on their host plants.",
            "fun_fact": f"{name} can help move pollen between flowering plants.",
        },
    }
    return {**shared, **category_copy[category]}


def quiz_for(name: str, fun_fact: str) -> str:
    return json.dumps(
        [{
            "question": f"Which statement about {name} is true?",
            "options": [
                fun_fact,
                "Wild animals are safest when people feed and touch them.",
                "Every Malaysian wildlife species lives in the ocean.",
            ],
            "correct_index": 0,
            "explanation": "Wildlife is best observed calmly and respectfully from a distance.",
        }],
        ensure_ascii=False,
    )


def build_block(records: list[dict[str, str]]) -> str:
    lines = [START, "-- Generated by rimbaquest/tools/complete_iteration1_species_data.py; do not edit manually."]
    for record in records:
        assignments = ", ".join(f"{key} = {quote(record[key])}" for key in (
            "habitat", "diet", "fun_fact", "threats", "conservation_status", "responsible_observation", "distinctive_features"
        ))
        lines.append(f"UPDATE species SET {assignments} WHERE id = {quote(record['id'])};")
    lines.append("DELETE FROM quizzes;")
    for index, record in enumerate(records, start=1):
        lines.append(
            "INSERT INTO quizzes (id, species_id, version, questions_json) VALUES "
            f"({index}, {quote(record['id'])}, 1, {quote(quiz_for(record['common_name'], record['fun_fact']))});"
        )
    lines.extend([END, ""])
    return "\n".join(lines)


def main() -> None:
    notes = curated_notes()
    with sqlite3.connect(DB_FILE) as connection:
        connection.row_factory = sqlite3.Row
        sighting_columns = {row[1] for row in connection.execute("PRAGMA table_info(sightings)")}
        if "recorded_at" not in sighting_columns:
            connection.execute("ALTER TABLE sightings ADD COLUMN recorded_at DATETIME")
        if "location_label" not in sighting_columns:
            connection.execute("ALTER TABLE sightings ADD COLUMN location_label VARCHAR")
        connection.execute("UPDATE sightings SET recorded_at = COALESCE(recorded_at, CURRENT_TIMESTAMP)")
        species = [dict(row) for row in connection.execute("SELECT id, common_name, category, habitat, diet, fun_fact, threats, conservation_status, responsible_observation, distinctive_features FROM species ORDER BY id")]
        completed = []
        for item in species:
            source = {**defaults(item["common_name"], item["category"]), **notes.get(item["id"], {})}
            record = {"id": item["id"], "common_name": item["common_name"]}
            for field in ("habitat", "diet", "fun_fact", "threats", "conservation_status", "responsible_observation", "distinctive_features"):
                record[field] = item[field] or source[field]
            completed.append(record)
            connection.execute(
                "UPDATE species SET habitat=?, diet=?, fun_fact=?, threats=?, conservation_status=?, responsible_observation=?, distinctive_features=? WHERE id=?",
                tuple(record[field] for field in ("habitat", "diet", "fun_fact", "threats", "conservation_status", "responsible_observation", "distinctive_features")) + (record["id"],),
            )
        connection.execute("DELETE FROM quizzes")
        connection.executemany(
            "INSERT INTO quizzes (id, species_id, version, questions_json) VALUES (?, ?, 1, ?)",
            [(index, item["id"], quiz_for(item["common_name"], item["fun_fact"])) for index, item in enumerate(completed, start=1)],
        )
        connection.execute("""UPDATE child_profiles SET xp = (
            SELECT COUNT(*) * 100 FROM collection_entries
            WHERE collection_entries.child_id = child_profiles.id
        )""")

    seed = SEED_FILE.read_text(encoding="utf-8")
    seed = re.sub(rf"\n?{re.escape(START)}.*?{re.escape(END)}\n?", "\n", seed, flags=re.DOTALL)
    SEED_FILE.write_text(seed.rstrip() + "\n\n" + build_block(completed), encoding="utf-8")
    print(f"Completed learning data and quizzes for {len(completed)} species")


if __name__ == "__main__":
    main()
