"""Synchronise bundled species-image metadata into the SQLite database and seed SQL.

The Expo client bundles images from ``assets/species`` directly.  The API stores
their stable, portable asset path (``/assets/species/<id>.jpg``), plus Commons
licence/source data when available.  Run this after adding a batch of images.
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
IMAGE_DIR = REPO_ROOT / "rimbaquest" / "assets" / "species"
ATTRIBUTION_FILE = IMAGE_DIR / "commons-attribution.json"
DATABASE_FILE = REPO_ROOT / "backend" / "data" / "RimbaQuest.db"
SEED_FILE = REPO_ROOT / "backend" / "data" / "seed.sql"
BLOCK_START = "-- BEGIN bundled species image metadata"
BLOCK_END = "-- END bundled species image metadata"


def sql(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def load_images() -> tuple[dict[str, str], dict[str, dict[str, object]]]:
    images = {path.stem: f"/assets/species/{path.name}" for path in IMAGE_DIR.glob("*.jpg")}
    attribution = json.loads(ATTRIBUTION_FILE.read_text(encoding="utf-8"))
    return images, attribution


def validate(images: dict[str, str]) -> tuple[set[str], set[str]]:
    with sqlite3.connect(DATABASE_FILE) as connection:
        database_ids = {row[0] for row in connection.execute("SELECT id FROM species")}
    return database_ids - images.keys(), images.keys() - database_ids


def update_database(images: dict[str, str], attribution: dict[str, dict[str, object]]) -> None:
    with sqlite3.connect(DATABASE_FILE) as connection:
        connection.execute("DELETE FROM species_images")
        for species_id, asset_path in sorted(images.items()):
            connection.execute("UPDATE species SET image_url = ? WHERE id = ?", (asset_path, species_id))
            metadata = attribution.get(species_id, {})
            source_url = metadata.get("page") or metadata.get("url")
            licence = metadata.get("licence")
            author = metadata.get("author")
            if source_url or licence or author:
                connection.execute(
                    "INSERT INTO species_images (species_id, uri, licence, attribution) VALUES (?, ?, ?, ?)",
                    (species_id, source_url or asset_path, licence, author),
                )


def build_seed_block(images: dict[str, str], attribution: dict[str, dict[str, object]]) -> str:
    lines = [BLOCK_START, "-- Generated by rimbaquest/tools/sync_species_image_metadata.py; do not edit manually."]
    for species_id, asset_path in sorted(images.items()):
        lines.append(f"UPDATE species SET image_url = {sql(asset_path)} WHERE id = {sql(species_id)};")
    lines.append("DELETE FROM species_images;")
    for species_id in sorted(images):
        metadata = attribution.get(species_id, {})
        source_url = metadata.get("page") or metadata.get("url")
        licence = metadata.get("licence")
        author = metadata.get("author")
        if source_url or licence or author:
            lines.append(
                "INSERT INTO species_images (species_id, uri, licence, attribution) VALUES "
                f"({sql(species_id)}, {sql(str(source_url) if source_url else None)}, "
                f"{sql(str(licence) if licence else None)}, {sql(str(author) if author else None)});"
            )
    lines.extend([BLOCK_END, ""])
    return "\n".join(lines)


def update_seed(images: dict[str, str], attribution: dict[str, dict[str, object]]) -> None:
    seed = SEED_FILE.read_text(encoding="utf-8")
    seed = re.sub(rf"\n?{re.escape(BLOCK_START)}.*?{re.escape(BLOCK_END)}\n?", "\n", seed, flags=re.DOTALL)
    SEED_FILE.write_text(seed.rstrip() + "\n\n" + build_seed_block(images, attribution), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true", help="write the database and seed SQL")
    args = parser.parse_args()
    images, attribution = load_images()
    missing, orphaned = validate(images)
    print(f"Bundled images matched to database species: {len(images) - len(orphaned)}")
    print(f"Database species without an image: {', '.join(sorted(missing)) or 'none'}")
    print(f"Image files without a database species: {', '.join(sorted(orphaned)) or 'none'}")
    print(f"Images with Commons metadata: {len(set(images) & set(attribution))}")
    if args.apply:
        update_database(images, attribution)
        update_seed(images, attribution)
        print("Updated backend/data/RimbaQuest.db and backend/data/seed.sql")


if __name__ == "__main__":
    main()
